# Generated by Django 3.2 on 2022-07-20 05:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='admin/post/images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='PressNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('content', tinymce.models.HTMLField(blank=True)),
            ],
        ),
    ]
