# Generated by Django 3.2 on 2022-07-20 05:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.CreateModel(
            name='AboutNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/%Y/%m/%d')),
                ('image_caption', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('subtitle', models.CharField(blank=True, default='', max_length=100)),
                ('body', tinymce.models.HTMLField(blank=True, default='')),
                ('paragraph_caption', models.CharField(default='', max_length=100)),
                ('paragraph_text', tinymce.models.HTMLField(blank=True, null=True)),
                ('paragraph_image', models.ImageField(blank=True, null=True, upload_to='manifesto/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('images', models.ManyToManyField(blank=True, related_name='about_images', to='home.AboutImage')),
            ],
            options={
                'verbose_name': 'Manifesto Note',
                'verbose_name_plural': 'Manifesto Notes',
            },
        ),
    ]
